version: 0.0
OS: linux
files:
   source:/index.html
   destination: /var/www/html/
   hooks:
      before install:
        location: scripts/install_dependencies
        timeout: 300
        runas: root
        location: scripts/starts_server
        timeout: 300
        runas: root
        
